import { Career, SimulationPath } from "@/types/careers";

export const careers: Career[] = [
  {
    id: "software-dev",
    title: "Software Developer",
    description: "Design and develop software applications and systems.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "Programming experience",
      "Problem-solving skills",
    ],
    salary_range: "$70,000 - $150,000",
    growth_rate: "22%",
    skills_required: ["JavaScript", "Python", "SQL", "Git", "Agile"],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Senior",
    industry: "Technology",
    related_careers: [
      "frontend-dev",
      "backend-dev",
      "devops-engineer",
      "systems-architect",
      "blockchain-dev",
    ],
    career_paths: [
      {
        title: "Frontend Specialist",
        description: "Focus on user interface and experience development",
        timeline: "2-3 years",
        requirements: ["React/Vue/Angular", "HTML/CSS", "UI/UX principles"],
        next_steps: [
          "Senior Frontend Developer",
          "UI/UX Engineer",
          "Technical Lead",
        ],
        potential_roles: [
          "UI Engineer",
          "Frontend Architect",
          "Web Performance Engineer",
        ],
      },
      {
        title: "Backend Specialist",
        description: "Focus on server-side development and databases",
        timeline: "2-3 years",
        requirements: ["Node.js/Java/Python", "Databases", "API Design"],
        next_steps: [
          "Senior Backend Developer",
          "System Architect",
          "Technical Lead",
        ],
        potential_roles: [
          "API Developer",
          "Database Engineer",
          "Cloud Engineer",
        ],
      },
    ],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    description:
      "Analyze and interpret complex data to help organizations make informed decisions.",
    requirements: [
      "Bachelor's degree in Data Science, Statistics, or related field",
      "Experience with data analysis tools",
      "Strong analytical skills",
    ],
    salary_range: "$85,000 - $165,000",
    growth_rate: "36%",
    skills_required: ["Python", "R", "SQL", "Machine Learning", "Tableau"],
    education_required: "Bachelor's Degree",
    experience_level: "Mid Level to Senior",
    industry: "Technology",
    related_careers: [
      "ml-engineer",
      "ai-research-scientist",
      "backend-dev",
      "data-analyst",
      "statistician",
    ],
    career_paths: [
      {
        title: "Machine Learning Specialist",
        description: "Focus on developing ML models and algorithms",
        timeline: "2-4 years",
        requirements: ["Deep Learning", "NLP", "Computer Vision"],
        next_steps: ["Senior ML Engineer", "AI Researcher", "ML Architect"],
        potential_roles: [
          "ML Operations Engineer",
          "AI Developer",
          "Research Scientist",
        ],
      },
      {
        title: "Analytics Leader",
        description: "Focus on business analytics and insights",
        timeline: "3-5 years",
        requirements: [
          "Business Intelligence",
          "Statistical Analysis",
          "Data Visualization",
        ],
        next_steps: [
          "Analytics Manager",
          "Chief Data Officer",
          "Analytics Director",
        ],
        potential_roles: [
          "Business Analytics Manager",
          "Data Strategy Lead",
          "Analytics Consultant",
        ],
      },
    ],
  },
  {
    id: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    description:
      "Protect organizations' computer systems and networks from cyber threats.",
    requirements: [
      "Bachelor's degree in Cybersecurity, Computer Science, or related field",
      "Knowledge of security protocols",
      "Attention to detail",
    ],
    salary_range: "$65,000 - $130,000",
    growth_rate: "33%",
    skills_required: [
      "Penetration Testing",
      "Firewalls",
      "Encryption",
      "Linux",
      "Ethical Hacking",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Mid Level",
    industry: "Technology",
    related_careers: [
      "security-engineer",
      "network-engineer",
      "systems-architect",
      "it-manager",
      "cloud-architect",
    ],
    career_paths: [
      {
        title: "Security Operations Specialist",
        description: "Focus on monitoring and responding to security incidents",
        timeline: "2-3 years",
        requirements: [
          "SIEM Tools",
          "Threat Intelligence",
          "Incident Response",
        ],
        next_steps: [
          "SOC Manager",
          "Security Operations Lead",
          "Incident Response Manager",
        ],
        potential_roles: [
          "Threat Hunter",
          "Security Analyst",
          "Incident Responder",
        ],
      },
      {
        title: "Security Architecture Specialist",
        description: "Focus on designing secure systems and infrastructure",
        timeline: "3-5 years",
        requirements: [
          "Network Security",
          "Cloud Security",
          "Security Frameworks",
        ],
        next_steps: ["Security Architect", "CISO", "Security Consultant"],
        potential_roles: [
          "Cloud Security Architect",
          "Security Solutions Architect",
          "Security Program Manager",
        ],
      },
    ],
  },
  {
    id: "cloud-architect",
    title: "Cloud Architect",
    description:
      "Design and manage cloud computing strategies for organizations to ensure scalability and security.",
    requirements: [
      "Bachelor's degree in Computer Science, IT, or related field",
      "Experience with cloud platforms",
      "Strategic thinking",
    ],
    salary_range: "$90,000 - $170,000",
    growth_rate: "15%",
    skills_required: ["AWS", "Azure", "Google Cloud", "DevOps", "Networking"],
    education_required: "Bachelor's Degree",
    experience_level: "Mid Level to Senior",
    industry: "Technology",
    related_careers: [
      "devops-engineer",
      "systems-architect",
      "security-engineer",
      "network-engineer",
      "it-manager",
    ],
    career_paths: [
      {
        title: "Cloud Solutions Architect",
        description: "Design comprehensive cloud solutions for enterprises",
        timeline: "4-6 years",
        requirements: [
          "Multi-cloud expertise",
          "Solution design",
          "Enterprise architecture",
        ],
        next_steps: [
          "Principal Cloud Architect",
          "Chief Cloud Architect",
          "Technical Director",
        ],
        potential_roles: [
          "Enterprise Architect",
          "Cloud Strategy Lead",
          "Digital Transformation Lead",
        ],
      },
      {
        title: "Cloud Security Specialist",
        description: "Focus on cloud security and compliance",
        timeline: "3-5 years",
        requirements: [
          "Security certifications",
          "Compliance frameworks",
          "Security architecture",
        ],
        next_steps: ["Cloud Security Architect", "Security Director", "CISO"],
        potential_roles: [
          "Security Architect",
          "Compliance Manager",
          "Security Consultant",
        ],
      },
    ],
  },
  {
    id: "ml-engineer",
    title: "Machine Learning Engineer",
    description:
      "Develop algorithms and models that enable machines to learn and make decisions.",
    requirements: [
      "Bachelor's degree in Computer Science, Mathematics, or related field",
      "Strong programming skills",
      "Knowledge of machine learning frameworks",
    ],
    salary_range: "$80,000 - $160,000",
    growth_rate: "36%",
    skills_required: [
      "Python",
      "TensorFlow",
      "Keras",
      "Data Modeling",
      "Statistics",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Mid Level to Senior",
    industry: "Technology",
    related_careers: [
      "data-scientist",
      "ai-research-scientist",
      "software-dev",
      "data-engineer",
      "backend-dev",
    ],
    career_paths: [
      {
        title: "Deep Learning Specialist",
        description: "Focus on neural networks and deep learning applications",
        timeline: "2-4 years",
        requirements: ["Neural Networks", "Computer Vision", "NLP"],
        next_steps: ["Senior ML Engineer", "AI Lead", "Research Scientist"],
        potential_roles: [
          "Computer Vision Engineer",
          "NLP Engineer",
          "AI Developer",
        ],
      },
      {
        title: "MLOps Engineer",
        description: "Focus on operationalizing ML models and systems",
        timeline: "2-3 years",
        requirements: ["CI/CD for ML", "Model Monitoring", "Docker/Kubernetes"],
        next_steps: [
          "MLOps Lead",
          "ML Platform Engineer",
          "ML Infrastructure Architect",
        ],
        potential_roles: [
          "ML Platform Engineer",
          "AI Infrastructure Engineer",
          "ML Systems Engineer",
        ],
      },
    ],
  },
  {
    id: "devops-engineer",
    title: "DevOps Engineer",
    description:
      "Bridge the gap between development and operations by automating and streamlining software delivery.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "Experience with CI/CD pipelines",
      "Collaboration skills",
    ],
    salary_range: "$75,000 - $140,000",
    growth_rate: "21%",
    skills_required: [
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Ansible",
      "Scripting",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Mid Level",
    industry: "Technology",
    related_careers: [
      "cloud-architect",
      "systems-architect",
      "software-dev",
      "backend-dev",
      "network-engineer",
    ],
    career_paths: [
      {
        title: "CI/CD Specialist",
        description: "Focus on continuous integration and delivery pipelines",
        timeline: "2-3 years",
        requirements: ["CI/CD Tools", "Automation Scripting", "Testing"],
        next_steps: ["DevOps Lead", "Automation Architect", "Release Manager"],
        potential_roles: [
          "CI/CD Engineer",
          "Automation Engineer",
          "Build & Release Engineer",
        ],
      },
      {
        title: "Infrastructure as Code Specialist",
        description: "Focus on infrastructure automation and management",
        timeline: "2-4 years",
        requirements: [
          "Terraform",
          "CloudFormation",
          "Configuration Management",
        ],
        next_steps: [
          "Infrastructure Architect",
          "Platform Engineer",
          "Cloud Operations Lead",
        ],
        potential_roles: [
          "Infrastructure Engineer",
          "Platform Engineer",
          "Site Reliability Engineer",
        ],
      },
    ],
  },
  {
    id: "blockchain-dev",
    title: "Blockchain Developer",
    description:
      "Design and implement decentralized applications using blockchain technology.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "Knowledge of cryptography",
      "Programming experience",
    ],
    salary_range: "$80,000 - $160,000",
    growth_rate: "25%",
    skills_required: [
      "Solidity",
      "Ethereum",
      "Smart Contracts",
      "Cryptography",
      "JavaScript",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Mid Level to Senior",
    industry: "Technology",
    related_careers: [
      "software-dev",
      "backend-dev",
      "security-engineer",
      "frontend-dev",
      "cryptographer",
    ],
    career_paths: [
      {
        title: "Smart Contract Developer",
        description: "Focus on developing and auditing smart contracts",
        timeline: "2-3 years",
        requirements: ["Solidity", "Smart Contract Security", "Testing"],
        next_steps: [
          "Lead Smart Contract Developer",
          "Blockchain Architect",
          "Security Auditor",
        ],
        potential_roles: [
          "Smart Contract Auditor",
          "DeFi Developer",
          "Protocol Engineer",
        ],
      },
      {
        title: "Blockchain Infrastructure Specialist",
        description:
          "Focus on blockchain protocol development and infrastructure",
        timeline: "3-5 years",
        requirements: [
          "Consensus Mechanisms",
          "P2P Networks",
          "Distributed Systems",
        ],
        next_steps: [
          "Blockchain Architect",
          "Protocol Engineer",
          "Research Scientist",
        ],
        potential_roles: [
          "Protocol Developer",
          "Core Blockchain Engineer",
          "Consensus Engineer",
        ],
      },
    ],
  },
  {
    id: "frontend-dev",
    title: "Frontend Developer",
    description:
      "Build and maintain the user-facing side of websites and applications.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "Experience with web development",
      "Attention to detail",
    ],
    salary_range: "$60,000 - $120,000",
    growth_rate: "13%",
    skills_required: ["HTML", "CSS", "JavaScript", "React", "UI Design"],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Mid Level",
    industry: "Technology",
    related_careers: [
      "software-dev",
      "ux-ui-designer",
      "backend-dev",
      "mobile-developer",
      "web-designer",
    ],
    career_paths: [
      {
        title: "UI Framework Specialist",
        description:
          "Focus on mastering frontend frameworks and component systems",
        timeline: "1-3 years",
        requirements: [
          "React/Vue/Angular",
          "State Management",
          "Component Design",
        ],
        next_steps: [
          "Senior Frontend Developer",
          "Frontend Architect",
          "Technical Lead",
        ],
        potential_roles: [
          "React Developer",
          "Frontend Framework Specialist",
          "UI Component Engineer",
        ],
      },
      {
        title: "Frontend Performance Engineer",
        description:
          "Focus on optimizing frontend performance and user experience",
        timeline: "2-4 years",
        requirements: [
          "Performance Optimization",
          "Web Vitals",
          "Browser Rendering",
        ],
        next_steps: [
          "Performance Lead",
          "Frontend Architect",
          "Web Platform Engineer",
        ],
        potential_roles: [
          "Web Performance Engineer",
          "Core Web Vitals Specialist",
          "Frontend Optimization Expert",
        ],
      },
    ],
  },
  {
    id: "it-manager",
    title: "IT Manager",
    description:
      "Oversee an organization's technology infrastructure and IT teams.",
    requirements: [
      "Bachelor's degree in Information Technology or related field",
      "Leadership experience",
      "Project management skills",
    ],
    salary_range: "$90,000 - $150,000",
    growth_rate: "11%",
    skills_required: [
      "Project Management",
      "Network Security",
      "Budgeting",
      "Leadership",
      "IT Strategy",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Senior",
    industry: "Technology",
    related_careers: [
      "systems-architect",
      "cloud-architect",
      "project-manager",
      "cto",
      "security-manager",
    ],
    career_paths: [
      {
        title: "IT Operations Director",
        description:
          "Focus on IT operations, infrastructure, and service delivery",
        timeline: "3-5 years",
        requirements: [
          "IT Operations",
          "Service Management",
          "Team Leadership",
        ],
        next_steps: ["IT Director", "CIO", "VP of IT Operations"],
        potential_roles: [
          "Head of IT Operations",
          "Infrastructure Manager",
          "Service Delivery Manager",
        ],
      },
      {
        title: "IT Strategy Leader",
        description: "Focus on IT strategy, governance, and transformation",
        timeline: "4-6 years",
        requirements: [
          "IT Governance",
          "Strategic Planning",
          "Digital Transformation",
        ],
        next_steps: ["CIO", "Chief Digital Officer", "IT Strategy Director"],
        potential_roles: [
          "IT Strategy Manager",
          "Digital Transformation Leader",
          "IT Governance Manager",
        ],
      },
    ],
  },
  {
    id: "ai-research-scientist",
    title: "AI Research Scientist",
    description:
      "Conduct research to advance artificial intelligence technologies.",
    requirements: [
      "PhD in Computer Science or related field",
      "Research experience",
      "Strong analytical skills",
    ],
    salary_range: "$100,000 - $200,000",
    growth_rate: "20%",
    skills_required: [
      "Machine Learning",
      "Deep Learning",
      "Python",
      "Research",
      "Statistics",
    ],
    education_required: "PhD",
    experience_level: "Senior",
    industry: "Technology",
    related_careers: [
      "ml-engineer",
      "data-scientist",
      "computational-linguist",
      "robotics-engineer",
      "research-director",
    ],
    career_paths: [
      {
        title: "Advanced AI Researcher",
        description: "Focus on pushing boundaries of AI technologies",
        timeline: "3-6 years",
        requirements: [
          "Research Publications",
          "Advanced ML",
          "Theoretical Foundations",
        ],
        next_steps: [
          "Principal Research Scientist",
          "Research Director",
          "AI Lab Leader",
        ],
        potential_roles: [
          "Lead AI Researcher",
          "Research Group Lead",
          "Distinguished Scientist",
        ],
      },
      {
        title: "Applied AI Research Leader",
        description: "Focus on applying AI research to practical applications",
        timeline: "3-5 years",
        requirements: [
          "Applied Research",
          "Prototype Development",
          "Industry Collaboration",
        ],
        next_steps: ["Applied Research Director", "AI Product Leader", "CTO"],
        potential_roles: [
          "Applied AI Research Lead",
          "AI Solutions Architect",
          "AI Innovation Lead",
        ],
      },
    ],
  },
  {
    id: "systems-architect",
    title: "Systems Architect",
    description: "Design and oversee the implementation of complex IT systems.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "Experience in systems design",
      "Leadership skills",
    ],
    salary_range: "$95,000 - $160,000",
    growth_rate: "10%",
    skills_required: [
      "Systems Design",
      "Cloud Computing",
      "Networking",
      "Leadership",
      "Problem-Solving",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Senior",
    industry: "Technology",
    related_careers: [
      "cloud-architect",
      "software-architect",
      "network-architect",
      "solution-architect",
      "enterprise-architect",
    ],
    career_paths: [
      {
        title: "Enterprise Solutions Architect",
        description:
          "Focus on enterprise-wide systems architecture and integration",
        timeline: "4-6 years",
        requirements: [
          "Enterprise Architecture",
          "System Integration",
          "Solution Design",
        ],
        next_steps: ["Chief Architect", "Enterprise Architect", "CTO"],
        potential_roles: [
          "Enterprise Solutions Architect",
          "Integration Architect",
          "Technical Director",
        ],
      },
      {
        title: "Security Architecture Specialist",
        description: "Focus on secure systems design and architecture",
        timeline: "3-5 years",
        requirements: [
          "Security Frameworks",
          "Threat Modeling",
          "Secure Design",
        ],
        next_steps: ["Chief Security Architect", "CISO", "Security Director"],
        potential_roles: [
          "Security Architect",
          "Secure Systems Designer",
          "Security Engineering Lead",
        ],
      },
    ],
  },
  {
    id: "backend-dev",
    title: "Backend Developer",
    description: "Develop and maintain server-side applications and databases.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "Experience with server-side programming",
      "Problem-solving skills",
    ],
    salary_range: "$65,000 - $130,000",
    growth_rate: "15%",
    skills_required: [
      "Node.js",
      "Java",
      "SQL",
      "API Development",
      "Database Management",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Mid Level",
    industry: "Technology",
    related_careers: [
      "software-dev",
      "frontend-dev",
      "database-administrator",
      "api-developer",
      "systems-programmer",
    ],
    career_paths: [
      {
        title: "API Development Specialist",
        description: "Focus on building and optimizing APIs and services",
        timeline: "2-3 years",
        requirements: ["RESTful APIs", "GraphQL", "Microservices"],
        next_steps: [
          "Senior Backend Developer",
          "API Architect",
          "Technical Lead",
        ],
        potential_roles: [
          "API Developer",
          "Services Engineer",
          "Integration Specialist",
        ],
      },
      {
        title: "Database Specialist",
        description: "Focus on database design, performance, and management",
        timeline: "2-4 years",
        requirements: [
          "Database Design",
          "Query Optimization",
          "Data Modeling",
        ],
        next_steps: [
          "Database Architect",
          "Data Engineer",
          "Backend Architect",
        ],
        potential_roles: [
          "Database Developer",
          "Data Platform Engineer",
          "Database Reliability Engineer",
        ],
      },
    ],
  },
  {
    id: "robotics-engineer",
    title: "Robotics Engineer",
    description:
      "Design and build robotic systems for automation and other applications.",
    requirements: [
      "Master's degree in Robotics or related field",
      "Experience with robotics programming",
      "Technical skills",
    ],
    salary_range: "$80,000 - $140,000",
    growth_rate: "9%",
    skills_required: [
      "ROS",
      "C++",
      "Python",
      "Mechanical Design",
      "Automation",
    ],
    education_required: "Master's Degree",
    experience_level: "Mid Level to Senior",
    industry: "Technology",
    related_careers: [
      "mechanical-engineer",
      "embedded-systems-engineer",
      "ai-research-scientist",
      "controls-engineer",
      "computer-vision-engineer",
    ],
    career_paths: [
      {
        title: "Robotics Software Specialist",
        description: "Focus on software development for robotic systems",
        timeline: "2-4 years",
        requirements: ["ROS", "Computer Vision", "Motion Planning"],
        next_steps: [
          "Senior Robotics Engineer",
          "Robotics Architect",
          "Technical Lead",
        ],
        potential_roles: [
          "Robotics Software Engineer",
          "Perception Engineer",
          "Motion Planning Engineer",
        ],
      },
      {
        title: "Robotics Hardware Specialist",
        description: "Focus on hardware design and integration for robotics",
        timeline: "3-5 years",
        requirements: [
          "Mechanical Design",
          "Embedded Systems",
          "Sensors and Actuators",
        ],
        next_steps: [
          "Robotics Hardware Lead",
          "Robotics Systems Architect",
          "Product Development Manager",
        ],
        potential_roles: [
          "Robotics Hardware Engineer",
          "Mechatronics Engineer",
          "Sensor Systems Engineer",
        ],
      },
    ],
  },
  // Design Field
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    description:
      "Create visual concepts to communicate ideas that inspire, inform, or captivate consumers.",
    requirements: [
      "Bachelor's degree in Graphic Design or related field",
      "Proficiency in design software",
      "Creativity and attention to detail",
    ],
    salary_range: "$40,000 - $85,000",
    growth_rate: "3%",
    skills_required: [
      "Adobe Photoshop",
      "Illustrator",
      "InDesign",
      "Typography",
      "Branding",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Mid Level",
    industry: "Design",
    related_careers: [
      "ux-ui-designer",
      "illustrator",
      "art-director",
      "brand-designer",
      "motion-graphics-designer",
    ],
    career_paths: [
      {
        title: "Brand Identity Designer",
        description: "Focus on creating and maintaining brand identities",
        timeline: "2-4 years",
        requirements: ["Branding", "Logo Design", "Brand Guidelines"],
        next_steps: [
          "Senior Brand Designer",
          "Art Director",
          "Creative Director",
        ],
        potential_roles: [
          "Brand Identity Designer",
          "Corporate Identity Designer",
          "Logo Specialist",
        ],
      },
      {
        title: "Print Design Specialist",
        description: "Focus on print media and publication design",
        timeline: "2-3 years",
        requirements: ["Print Production", "Layout Design", "Typography"],
        next_steps: [
          "Senior Print Designer",
          "Publication Art Director",
          "Production Manager",
        ],
        potential_roles: [
          "Publication Designer",
          "Package Designer",
          "Print Production Artist",
        ],
      },
    ],
  },
  {
    id: "ux-ui-designer",
    title: "UX/UI Designer",
    description:
      "Design user-friendly interfaces and experiences for digital products like apps and websites.",
    requirements: [
      "Bachelor's degree in Design, Human-Computer Interaction, or related field",
      "Understanding of user-centered design principles",
      "Collaboration skills",
    ],
    salary_range: "$60,000 - $120,000",
    growth_rate: "8%",
    skills_required: [
      "Figma",
      "Sketch",
      "Wireframing",
      "Prototyping",
      "User Research",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Senior",
    industry: "Design",
    related_careers: [
      "graphic-designer",
      "product-designer",
      "frontend-dev",
      "interaction-designer",
      "web-designer",
    ],
    career_paths: [
      {
        title: "UX Researcher",
        description: "Focus on user research and testing",
        timeline: "2-4 years",
        requirements: ["User Research", "Usability Testing", "Data Analysis"],
        next_steps: ["Senior UX Researcher", "Research Lead", "UX Manager"],
        potential_roles: [
          "User Researcher",
          "Usability Specialist",
          "Design Strategist",
        ],
      },
      {
        title: "UI Designer",
        description: "Focus on visual design and interfaces",
        timeline: "2-3 years",
        requirements: ["Visual Design", "Design Systems", "Typography"],
        next_steps: ["Senior UI Designer", "Design Lead", "Art Director"],
        potential_roles: [
          "Visual Designer",
          "Design System Manager",
          "Brand Designer",
        ],
      },
    ],
  },
  {
    id: "industrial-designer",
    title: "Industrial Designer",
    description:
      "Design and develop manufactured products, such as cars, appliances, and furniture, focusing on usability and aesthetics.",
    requirements: [
      "Bachelor's degree in Industrial Design or related field",
      "Proficiency in 3D modeling software",
      "Creativity and technical skills",
    ],
    salary_range: "$50,000 - $90,000",
    growth_rate: "2%",
    skills_required: [
      "CAD",
      "3D Rendering",
      "Prototyping",
      "Material Science",
      "Sketching",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Mid Level",
    industry: "Design",
    related_careers: [
      "product-designer",
      "mechanical-engineer",
      "furniture-designer",
      "automotive-designer",
      "cad-technician",
    ],
    career_paths: [
      {
        title: "Product Design Specialist",
        description: "Focus on consumer product design and development",
        timeline: "2-4 years",
        requirements: ["Consumer Products", "Ergonomics", "Manufacturing"],
        next_steps: [
          "Senior Product Designer",
          "Design Manager",
          "Creative Director",
        ],
        potential_roles: [
          "Consumer Product Designer",
          "Product Development Specialist",
          "Design Consultant",
        ],
      },
      {
        title: "Transportation Designer",
        description: "Focus on automotive and transportation design",
        timeline: "3-5 years",
        requirements: [
          "Transportation Design",
          "Aerodynamics",
          "Automotive Systems",
        ],
        next_steps: [
          "Senior Transportation Designer",
          "Design Director",
          "Chief Designer",
        ],
        potential_roles: [
          "Automotive Designer",
          "Aviation Designer",
          "Marine Designer",
        ],
      },
    ],
  },
  {
    id: "motion-graphics-designer",
    title: "Motion Graphics Designer",
    description:
      "Create animated graphics and visual effects for films, TV, and digital media.",
    requirements: [
      "Bachelor's degree in Graphic Design, Animation, or related field",
      "Experience with animation software",
      "Storytelling skills",
    ],
    salary_range: "$45,000 - $100,000",
    growth_rate: "4%",
    skills_required: [
      "After Effects",
      "Cinema 4D",
      "Animation",
      "Storyboarding",
      "Adobe Premiere",
    ],
    education_required: "Bachelor's Degree",
    experience_level: "Entry Level to Mid Level",
    industry: "Design",
    related_careers: [
      "graphic-designer",
      "animator",
      "video-editor",
      "vfx-artist",
      "ui-animator",
    ],
    career_paths: [
      {
        title: "Broadcast Graphics Specialist",
        description: "Focus on creating motion graphics for TV and broadcast",
        timeline: "2-3 years",
        requirements: ["Broadcast Design", "Lower Thirds", "Title Sequences"],
        next_steps: [
          "Senior Motion Designer",
          "Broadcast Art Director",
          "Creative Director",
        ],
        potential_roles: [
          "Broadcast Designer",
          "News Graphics Specialist",
          "Title Sequence Designer",
        ],
      },
      {
        title: "Digital Animation Specialist",
        description: "Focus on animated content for digital platforms",
        timeline: "2-4 years",
        requirements: [
          "Character Animation",
          "Social Media Content",
          "Interactive Graphics",
        ],
        next_steps: [
          "Animation Director",
          "Digital Content Lead",
          "Creative Director",
        ],
        potential_roles: [
          "Digital Animator",
          "Explainer Video Creator",
          "Social Media Animator",
        ],
      },
    ],
  },
];

export const simulationPaths: SimulationPath[] = [
  {
    id: "software-dev",
    title: "Software Developer",
    description: "Design and develop software applications and systems",
    averageSalary: "$105,000/year",
    growthRate: "25%",
    requiredSkills: [
      "JavaScript",
      "Python",
      "Problem Solving",
      "System Design",
    ],
    timeToAchieve: "2-4 years",
    steps: [
      "Learn programming fundamentals",
      "Build personal projects",
      "Internship/Entry level position",
      "Gain specialized expertise",
    ],
    trending: true,
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    description: "Analyze complex data sets to help guide business decisions",
    averageSalary: "$120,000/year",
    growthRate: "30%",
    requiredSkills: ["Python", "Statistics", "Machine Learning", "SQL"],
    timeToAchieve: "3-5 years",
    steps: [
      "Master statistics and mathematics",
      "Learn data analysis tools",
      "Practice with real datasets",
      "Develop ML expertise",
    ],
    trending: true,
  },
  {
    id: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    description:
      "Protect organizations' systems and networks from cyber threats",
    averageSalary: "$95,000/year",
    growthRate: "33%",
    requiredSkills: [
      "Penetration Testing",
      "Security Protocols",
      "Network Security",
      "Ethical Hacking",
    ],
    timeToAchieve: "2-3 years",
    steps: [
      "Learn cybersecurity fundamentals",
      "Get security certifications",
      "Build security projects",
      "Develop specialized knowledge",
    ],
    trending: true,
  },
  {
    id: "cloud-architect",
    title: "Cloud Architect",
    description: "Design and oversee cloud computing strategies",
    averageSalary: "$150,000/year",
    growthRate: "35%",
    requiredSkills: [
      "AWS/Azure",
      "Network Security",
      "System Architecture",
      "DevOps",
    ],
    timeToAchieve: "5-7 years",
    steps: [
      "Get cloud certifications",
      "Gain infrastructure experience",
      "Learn security best practices",
      "Master cloud platforms",
    ],
    trending: true,
  },
  {
    id: "ux-ui-designer",
    title: "UX/UI Designer",
    description: "Design user-friendly interfaces and experiences",
    averageSalary: "$95,000/year",
    growthRate: "20%",
    requiredSkills: [
      "UI Design",
      "User Research",
      "Prototyping",
      "Wireframing",
    ],
    timeToAchieve: "2-3 years",
    steps: [
      "Learn design principles",
      "Master design tools",
      "Build portfolio",
      "Get certified",
    ],
    trending: false,
  },
  {
    id: "healthcare-admin",
    title: "Healthcare Administrator",
    description: "Manage healthcare facilities and operations",
    averageSalary: "$110,000/year",
    growthRate: "20%",
    requiredSkills: [
      "Healthcare Policy",
      "Financial Management",
      "Leadership",
      "Compliance",
    ],
    timeToAchieve: "4-6 years",
    steps: [
      "Get healthcare administration degree",
      "Gain experience in healthcare",
      "Develop leadership skills",
      "Learn healthcare regulations",
    ],
    trending: true,
  },
];

export const industries = [
  "Technology",
  "Design",
  "Healthcare",
  "Finance",
  "Education",
  "Engineering",
  "Marketing",
  "Environmental Sciences",
  "Arts",
];

export const experienceLevels = [
  "Entry Level",
  "Mid Level",
  "Senior",
  "Entry Level to Mid Level",
  "Mid Level to Senior",
  "Entry Level to Senior",
];

export const educationLevels = [
  "High School",
  "Some College",
  "Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "PhD",
];
